apiVersion: v1
kind: ConfigMap
metadata:
  name: mqm-demo-mq-web
data:
  mqwebuser.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
        <featureManager>
            <feature>appSecurity-2.0</feature>
            <feature>basicAuthenticationMQ-1.0</feature>
        </featureManager>
        <enterpriseApplication id="com.ibm.mq.console">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="MQWebUI" realm="defaultRealm"/>
                </security-role>
            </application-bnd>
        </enterpriseApplication>
        <enterpriseApplication id="com.ibm.mq.rest">
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <group name="MQWebUI" realm="defaultRealm"/>
                </security-role>
                <security-role name="MQWebUser">
                    <group name="MQWebMessaging" realm="defaultRealm"/>
                </security-role>
            </application-bnd>
        </enterpriseApplication>
        <basicRegistry id="basic" realm="defaultRealm">
            <user name="admin" password="passw0rd"/>
            <user name="app" password="passw0rd"/>
            <group name="MQWebUI">
                <member name="admin"/>
            </group>
            <group name="MQWebMessaging">
                <member name="app"/>
            </group>
        </basicRegistry>
        <variable name="httpHost" value="*"/>
        <variable name="managementMode" value="externallyprovisioned"/>
        <variable name="mqConsoleRemoteSupportEnabled" value="false"/>
        <variable name="mqConsoleEnableUnsafeInline" value="true"/>
        <jndiEntry jndiName="mqConsoleDefaultCCDTHostname" value="${env.MQ_CONSOLE_DEFAULT_CCDT_HOSTNAME}"/>
        <jndiEntry jndiName="mqConsoleDefaultCCDTPort" value="${env.MQ_CONSOLE_DEFAULT_CCDT_PORT}"/>
        <httpDispatcher enableWelcomePage="false" appOrContextRootMissingMessage='&lt;script&gt;document.location.href="/ibmmq/console/";&lt;/script&gt;' />
        <include location="tls.xml"/>
    </server>

